#!/bin/bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  echo -n "Git email: "
  read gitemail
  git config --global user.email $gitemail
  success 'gitconfig'
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi

  done
}

setup_gitconfig
install_dotfiles

# Install homebrew and OS X specific apps
if [ $(uname) == "Darwin" ]; then
  which -s brew
  if [[ $? != 0  ]] ; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  # Install all the brew goodies.
  /usr/local/bin/brew update
  /usr/local/bin/brew upgrade
  /usr/local/bin/brew install
  /usr/local/bin/brew rbenv
  /usr/local/bin/brew ansible
  /usr/local/bin/brew ctags
  /usr/local/bin/brew git
  /usr/local/bin/brew git-flow
  /usr/local/bin/brew hub
  /usr/local/bin/brew jo
  /usr/local/bin/brew jsonpp
  /usr/local/bin/brew liquidprompt
  /usr/local/bin/brew mariadb
  /usr/local/bin/brew nmap
  /usr/local/bin/brew reattach-to-user-namespace
  /usr/local/bin/brew ssh-copy-id
  /usr/local/bin/brew the_silver_searcher
  /usr/local/bin/brew tig
  /usr/local/bin/brew tmux
  /usr/local/bin/brew tree
  /usr/local/bin/brew vim
  /usr/local/bin/brew watch
  /usr/local/bin/brew wget
  /usr/local/bin/brew cowsay
  /usr/local/bin/brew fortune

  # Install zsh syntax highlighting.
  if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  fi

  # Download gruvbox for iTerm2.
  if [ ! -f ~/bin/gruvbox-dark.itermcolors ]; then
    cd ~/bin && wget https://raw.githubusercontent.com/morhetz/gruvbox-contrib/master/iterm2/gruvbox-dark.itermcolors
  fi

  # Install Sack.
  if [ ! -d ~/dotfiles/bin/sack ]; then
    git clone https://github.com/sampson-chen/sack.git ~/dotfiles/bin/sack && cd ~/dotfiles/bin/sack && chmod +x install_sack.sh && ./install_sack.sh
  fi

  # Install nvm and global node.
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh"
  nvm install node

  # Install npm packags.
  if [ $(uname) == "Darwin" ]; then
    npm install -g gatsby-cli
    npm install -g firebase-tools
  fi

  # Install rvm and global ruby
  curl -sSL https://get.rvm.io | bash -s stable
  export PATH="$PATH:$HOME/.rvm/bin"
  export RBENV_ROOT=/usr/local/var/rbenv
  rbenv install 2.3.0
  rbenv global 2.3.0

  # Install lolcat for pretty colors
  gem install lolcat
  echo "Installed lolcat"

  # Install Monaco for Powerline font.
  cp ~/dotfiles/fonts/MonacoforPowerline.otf /Library/Fonts
fi

# Install Plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install plugins
vim +PlugInstall +qall now

# Install Composer
curl -Ss https://getcomposer.org/installer | php
if [ $(uname) == "Darwin" ]; then
  mv composer.phar /usr/local/bin/composer
  else sudo mv composer.phar /usr/local/bin/composer
fi

# Install Drupal Console
curl https://drupalconsole.com/installer -L -o drupal.phar
mv drupal.phar /usr/local/bin/drupal
chmod +x /usr/local/bin/drupal
drupal init --override
drupal check

# Install Drush and related drush tools
composer global require drush/drush:^8.1.0 \
drush/config-extra \
hirak/prestissimo \
pantheon-systems/terminus \
squizlabs/php_codesniffer \
dealerdirect/phpcodesniffer-composer-installer \
drupal/coder

# Run Composer global update.
composer global update


if [ ! -d "$HOME/.drush" ]; then
  mkdir -p $HOME/.drush
fi

drush cc drush

if [ ! -d "$HOME/.drush/composer_generate" ]; then
  git clone --branch 7.x-1.x https://git.drupal.org/project/composer_generate.git $HOME/.drush/composer_generate
  cd $HOME/.drush/composer_generate
  git checkout tags/7.x-1.3 -b 7.x-1.3
  cd -
fi

if [ ! -d "$HOME/.drush/drupalgeddon" ]; then
  git clone --branch 7.x-1.x https://git.drupal.org/project/drupalgeddon.git $HOME/.drush/drupalgeddon
  cd -
fi

if [ ! -d "$HOME/.drush/registry_rebuild" ]; then
  git clone --branch 7.x-2.x https://git.drupal.org/project/registry_rebuild.git $HOME/.drush/registry_rebuild
  cd $HOME/.drush/registry_rebuild
  git checkout tags/7.x-2.3 -b 7.x-2.3
  cd -
fi

if [ ! -d "$HOME/.drush/security_review" ]; then
  git clone --branch 7.x-1.x https://git.drupal.org/project/security_review.git $HOME/.drush/security_review
  cd $HOME/.drush/security_review
  git checkout tags/7.x-1.2 -b 7.x-1.2
  cd -
fi

if [ ! -d "$HOME/.drush/securitytesting" ]; then
  git clone --branch 7.x-1.x https://git.drupal.org/project/securitytesting.git $HOME/.drush/securitytesting
  cd -
fi

if [ ! -d "$HOME/.drush/sensitive_data" ]; then
  git clone --branch 7.x-1.x https://git.drupal.org/project/sensitive_data.git $HOME/.drush/sensitive_data
  cd $HOME/.drush/sensitive_data
  git checkout tags/7.x-1.0 -b 7.x-1.0
  cd -
fi

if [ ! -d "$HOME/.drush/site_audit" ]; then
  git clone --branch 7.x-1.x https://git.drupal.org/project/site_audit.git $HOME/.drush/site_audit
  cd $HOME/.drush/site_audit
  git checkout tags/7.x-1.16 -b 7.x-1.16
  composer install
  cd -
fi

if [ ! -d "$HOME/.drush/unused_modules" ]; then
  git clone --branch 7.x-1.x https://git.drupal.org/project/unused_modules.git $HOME/.drush/unused_modules
  cd $HOME/.drush/unused_modules
  git checkout tags/7.x-1.5 -b 7.x-1.5
  cd -
fi

drush cc drush

# Install Wodby CLI
if [ $(uname) == "Darwin" ]; then
  export WODBY_CLI_LATEST_URL=$(curl -s https://api.github.com/repos/wodby/wodby-cli/releases/latest | grep darwin-amd64 | grep browser_download_url | cut -d '"' -f 4)
  wget -qO- "${WODBY_CLI_LATEST_URL}" | tar xz -C /usr/local/bin
fi

echo ''
echo '  All installed!'

